### ISSUE TITLE
为什么不用公共的评论系统呢

### ISSUE THREAD

**Issue by weaming** [keakon/Doodle#1]
比如 Disqus.

**Comment by keakon** [comment]
1. 自己实现评论会有最好的可控性和定制性，包括评论数据的格式化、编辑和展示等。  
   例如：
   - 博客的管理员有特殊需求的话，可以直接裸写 HTML 的评论。
   - 有违规或误用的情况发生的话，可以修改其他用户的评论和资料。
   - 可以方便地获取评论数据，用于在侧边栏和评论 feed 中展示。
2. 需要承担第三方评论系统停止服务或服务故障的风险，以及可能的迁移成本。

**Comment by flyher** [comment]
@keakon 
可否有用户摆脱谷歌账户来留言的的办法？
类似wp自带的留言版

**Comment by keakon** [comment]
@flyher 验证用户会比较麻烦，不验证容易被 spam，而且无法用邮件通知。也想过用微博、微信登录，但都拿不到邮箱地址。

**Comment by flyher** [comment]
@keakon 
我之前在文章页面下面加了多说的js评论框，但是后来发现多说可能会收集个人信息，如你上面说的，第三方评论始终具有局限性。

想到除了少数程序员能够使用代理工具登录谷歌账户留言，这样受众面就有些限制性了。

留言内容既能保存到自己的数据库中，又能够让其它用户不被谷歌账户限制，想到的也就只有wp的留言模式了。

**Comment by keakon** [comment]
@flyher 我觉得这对我来说反而是好事，由墙帮我防 spam。

最初我没考虑自己做注册，所以没考虑邮件的事。
后来发现邮件通知很重要，于是就集成了 mailgun 的邮件服务，每个月能发 1 万封免费邮件，对大部分博客来说已经足够了。
有兴趣的话，任何人都可以自己去实现邮件验证，这也是开源的好处。但这对我来说不是一个必要的功能，所以今年应该不会去做。
