### ISSUE TITLE
谷歌授权登录无法留言

### ISSUE THREAD

**Issue by flyher** [keakon/Doodle#2]
在你某篇博文下右上角，登录=>谷歌登录=>授权=>然后直接跳到博文页面，上面也没显示登录后的信息，下面也没显示留言框。

update:2016-02-26
今天居然可以了，你最近改过代码？

**Comment by keakon** [comment]
2 月 25 日凌晨 4 点半尝试修了这个 bug，但好像你是在之后遇到的问题。

**Comment by flyher** [comment]
看了谷歌的最近使用过的设备，貌似是  2月24日下午5:37，如果是这个时间的话就说明你修正过了。
很遗憾之前的授权邮件删除了，没找到具体时间，

**Comment by keakon** [comment]
@flyher 行，那我先关闭了。之前在 localStorage 里保存了登录/退出登录的时间，但未登录时会保存为 "undefined"，然后比较时间时就出错了。现在会判定不是数字时，就清空 localStorage。
