### ISSUE TITLE
没有doodle.main文件

### ISSUE THREAD

**Issue by luckypoem** [keakon/Doodle#7]
hi.

root@ar:~/doodle# ls
LICENSE  README.md  conf  docker  doodle  fabfile.py  requirements.txt	scripts
root@ar:~/doodle# find . -name doodle.main
root@ar:~/doodle#

**Comment by keakon** [comment]
是 doodle/main.py 文件：
https://github.com/keakon/Doodle/blob/master/doodle/main.py
